'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowRight, Check, CheckCircle2, Circle, Cpu, Download, ExternalLink, Gauge, PackageOpen, RotateCw, ShieldCheck, Wrench } from 'lucide-react';

type Step = { id: string; title: string; outcome: string; actions: string[]; gate: string };

const steps: Step[] = [
  { id:'scope', title:'Lock Rev A', outcome:'A buildable target, not a shrinking wish-list.', actions:['52 positions, forward rotation only','Proven 54 × 43 × 0.762 mm CR80 flap halves','Approx. 60 mm drum; expect 125–145 mm module height','One MCU, driver, Hall sensor and RS-485 transceiver per character'], gate:'Do not customise dimensions until a proven mechanism moves.' },
  { id:'coupon', title:'Print fit coupons', outcome:'Your printer tells us the real tolerances.', actions:['Test flap pivot slots at nominal, +0.1, +0.2 and +0.3 mm','Test the motor shaft socket and M3 free-side axle','Test magnet pockets before inserting a magnet','Write the winning dimensions on the parts'], gate:'Every fit is firm but movable; nothing needs forcing.' },
  { id:'gravity', title:'Make a 3–5 flap gravity rig', outcome:'Prove the hardest mechanical action before spending more.', actions:['Cut CR80 cards in half with a printed jig','Punch identical pivot tabs/notches','Mount only 3–5 flaps and turn by hand','Adjust the pawl/backstop until every flap falls cleanly'], gate:'100 hand-turned cycles with zero jams.' },
  { id:'powered', title:'Build a 10–12 position powered drum', outcome:'Cheaply test motor, noise, speed and homing.', actions:['Plug the 28BYJ-48 into its ULN2003 board','Connect a pre-headered ESP32-C3 using female leads','Connect a pre-built Hall board and one rotor magnet','Measure motor winding resistance and actual steps per revolution'], gate:'100 powered cycles; home is found at the same point every time.' },
  { id:'full', title:'Build character module 01', outcome:'One complete 52-position character.', actions:['Cut and label all 52 flap halves','Install the M3 free-side axle, drum and adjustable pawl','Add the 3.3 V MAX3485 RS-485 module','Save module ID 01 in MCU flash'], gate:'1,000 cycles with no jam, stall or missed-home event.' },
  { id:'twin', title:'Duplicate module 02', outcome:'Two truly independent modules.', actions:['Build from the same files and recorded tolerances','Save ID 02','Join A/B/GND/power on a short linear bus','Terminate only the two physical ends of the RS-485 trunk'], gate:'Send different targets to IDs 01 and 02 for 500 mixed moves.' },
  { id:'pi', title:'Build the Pi controller', outcome:'The brain sends commands; it never drives a motor.', actions:['Install Raspberry Pi OS Lite on microSD','Plug in a USB-to-RS-485 adapter—no GPIO header required','Run the controller service and discover IDs 01 and 02','Send target positions and read status/fault replies'], gate:'Unplug the Pi: both visible characters stay where they are.' },
  { id:'edges', title:'Test snap-together edges', outcome:'Only now validate the modular promise.', actions:['Print alignment peg/socket coupons','Use magnets for holding, geometry for alignment','Prototype spring pogo pins against large ENIG pads','Cycle the joint 250 times while checking voltage and packets'], gate:'No intermittent power/data and no sliding under module weight.' },
];

const bom = [
  { group:'Per module', item:'ESP32-C3 Mini, fitted headers', qty:'1', price:'$7.60', source:'Core Electronics', url:'https://core-electronics.com.au/esp32-c3-mini-dev-board-risc-v-processor-wi-fi-bt5-smd-compatible.html', note:'Local; AU$7+ shipping. Confirm fitted headers.' },
  { group:'Per module', item:'28BYJ-48 + ULN2003 board', qty:'1', price:'$6.96 delivered example', source:'eBay AU', url:'https://www.ebay.com.au/b/Unbranded-Industrial-Stepper-Motors/9723/bn_18937908', note:'Marketplace price varies. Verify voltage, plug and fitted pins.' },
  { group:'Per module', item:'MAX3485 3.3 V RS-485 module', qty:'1', price:'$5.00', source:'KiwiGuy', url:'https://kiwiguycomputers.com.au/product/max3485-ttl-to-rs485-module/', note:'AU$10 shipping. Confirm headers are installed.' },
  { group:'Shared for two', item:'100 × CR80 30 mil PVC cards', qty:'1 pack', price:'$26.73 inc GST', source:'Peacock Bros', url:'https://shop.peacocks.com.au/category/label-printers-and-supplies/id-card-printer-supplies/id-cards', note:'Cut in half: enough for about two 52-flap modules.' },
  { group:'Shared for two', item:'5 × Hall sensor boards', qty:'1 pack', price:'$4.78 delivered example', source:'eBay AU', url:'https://www.ebay.com.au/shop/sensor-hall-effect?_nkw=sensor+hall+effect', note:'Verify unipolar/non-latching behaviour and fitted headers.' },
  { group:'Shared for two', item:'40 × female/female leads', qty:'1 ribbon', price:'$3.20', source:'Core Electronics', url:'https://core-electronics.com.au/prototyping/prototyping-wire/female-female.html', note:'Prototype logic only; not the final power connector.' },
  { group:'Shared for two', item:'3 × 2 mm magnets', qty:'20 MOQ', price:'$8.60', source:'AMF Magnetics', url:'https://magnet.com.au/products/neodymium-disc-3mm-x-2mm', note:'Keep away from children; verify sensing distance.' },
  { group:'Controller', item:'Raspberry Pi Zero W', qty:'1', price:'$25.90', source:'Core Electronics', url:'https://core-electronics.com.au/raspberry-pi/boards/zero.html', note:'Cheapest in-stock Pi checked. Zero 2 W was $30.20, out of stock.' },
  { group:'Controller', item:'USB-RS-485 adapter, screw terminals', qty:'1', price:'$39.95 local', source:'Core Electronics', url:'https://core-electronics.com.au/usb-to-multi-protocol-serial-adapter-rs232-ttl-uart-rs485-adafruit.html', note:'Verified no-solder local option; cheaper marketplace adapters exist.' },
];

const makers = [
  { name:'Plastics Australia', place:'Nundah, QLD', job:'PP die-cutting + creasing', price:'Quote only', url:'https://plasticsaust.com.au/product/die-cutting-creasing/' },
  { name:'Acme Preston', place:'Smithfield, NSW', job:'Polypropylene die cutting', price:'Quote only', url:'https://www.acmepreston.com.au/polypropylene-cutting/' },
  { name:'JLCPCB', place:'Overseas', job:'Factory-assembled module PCB', price:'US$8.18 setup + parts/assembly', url:'https://jlcpcb.com/help/article/pcb-assembly-price' },
  { name:'Stencils Australia', place:'Bayswater, VIC', job:'CNC-routed plastic', price:'Quote only', url:'https://stencilsaustralia.com.au/custom-stencils/' },
];

const alphabet = ['SPACE',...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),...'0123456789'.split(''),'.',',',':',';','!','?','-','+','/','=','#','@','&','(',')'];

export default function Home() {
  const [done,setDone] = useState<string[]>([]);
  const [moduleCount,setModuleCount] = useState(2);
  useEffect(()=>{ try { setDone(JSON.parse(localStorage.getItem('msf-progress') || '[]')); } catch {} },[]);
  const toggle=(id:string)=>setDone(prev=>{ const next=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]; localStorage.setItem('msf-progress',JSON.stringify(next)); return next; });
  const estimate = moduleCount * 37.5;

  return <main>
    <header className="topbar">
      <a className="brand" href="#top"><span className="brand-mark">MS</span><span>MODULAR SPLITFLAP</span></a>
      <nav><a href="#plan">Build</a><a href="#buy">Buy</a><a href="#architecture">System</a><a href="#manufacture">Manufacture</a></nav>
      <span className="status"><i /> REV A · 04 SEP 2026</span>
    </header>

    <section className="hero" id="top">
      <div className="hero-copy"><p className="eyebrow">OPEN-SOURCE · TWO CHARACTERS FIRST</p><h1>Build one flap.<br/><em>Then prove the bus.</em></h1><p className="lede">A researched, no-solder path from printed parts to two independently addressed split-flap modules and a Raspberry Pi controller.</p><div className="hero-actions"><a className="button primary" href="#plan">Start at step 0 <ArrowRight size={16}/></a><a className="button secondary" href="#buy">See the real cost</a></div></div>
      <div className="module-card"><div className="module-topline"><span>MODULE 01</span><span>POSITION 01 / 52</span></div><div className="flap-display"><div className="flap upper">A</div><div className="hinge"/><div className="flap lower">A</div></div><div className="module-meta"><span><Cpu size={15}/> OWN MCU</span><span><RotateCw size={15}/> FORWARD</span><span><Gauge size={15}/> HALL HOME</span></div></div>
    </section>

    <section className="truth-strip"><div><span className="metric">AU$37–45</span><span className="metric-label">honest full-module estimate*</span></div><p><strong>The AU$20–30 target is a stretch, not a promise.</strong> It works for a reduced-flap mechanical proof using existing consumables. A complete 52-flap, no-solder RS-485 module costs more at one-off quantities; Pi and shipping are separate.</p></section>

    <section className="section decision"><div className="section-heading"><p className="eyebrow">DECISIONS, NOT GUESSES</p><h2>The Rev-A specification</h2></div><div className="spec-grid">
      <div><small>POSITIONS</small><strong>52</strong><p>SPACE + A–Z + 0–9 + 15 symbols</p></div><div><small>FLAP HALF</small><strong>54 × 43 mm</strong><p>0.762 mm CR80 PVC; proven baseline</p></div><div><small>VISIBLE FACE</small><strong>≈54 × 86 mm</strong><p>The earlier 50 × 70 mm target becomes a later experiment</p></div><div><small>DRUM</small><strong>≈60 mm Ø</strong><p>Forward-only; no shortest-path reverse</p></div><div><small>MODULE</small><strong>≈125–145 mm high</strong><p>Final width/depth follow physical testing</p></div><div><small>CONTROL</small><strong>One MCU each</strong><p>The Pi sends ID + target position only</p></div>
    </div><div className="evidence"><ShieldCheck size={20}/><p><strong>Why these dimensions?</strong> Scott Bezek’s stable v2 openly supports 52 positions with 54 × 43 × 0.762 mm halves. The smaller original enclosure estimate conflicts with the rotating envelope.</p><a href="https://github.com/scottbez1/splitflap/blob/master/3d/flap_dimensions.scad" target="_blank">Inspect source CAD <ExternalLink size={13}/></a></div></section>

    <section className="section plan" id="plan"><div className="section-heading"><p className="eyebrow">BUILD ORDER · SAVES ON THIS DEVICE</p><h2>Pass each gate before continuing.</h2><p>Your checkmarks stay in this browser. A failed gate means adjust and repeat—not buy more parts.</p></div><div className="progress"><span style={{width:(done.length/steps.length*100)+'%'}}/><b>{done.length}/{steps.length} gates passed</b></div><div className="steps">{steps.map((s,i)=><article className={done.includes(s.id)?'build-step complete':'build-step'} key={s.id}><button className="check" onClick={()=>toggle(s.id)} aria-label={'Mark '+s.title+' complete'}>{done.includes(s.id)?<CheckCircle2/>:<Circle/>}</button><div className="step-no">{String(i).padStart(2,'0')}</div><div><h3>{s.title}</h3><p className="outcome">{s.outcome}</p><ul>{s.actions.map(a=><li key={a}>{a}</li>)}</ul><p className="gate"><Check size={14}/><strong>PASS GATE:</strong> {s.gate}</p></div></article>)}</div></section>

    <section className="reference"><img src="/splitflap-reference.jpg" alt="Scott Bezek split-flap reference mechanism showing a numbered flap drum and electronics"/><div><p className="eyebrow">PROVEN REFERENCE, NOT OUR FINAL CAD</p><h2>Learn from hardware that already works.</h2><p>Scott Bezek’s Apache-2.0 project supplies tested 52-flap geometry, calibration logic and manufacturing lessons. Rev A starts there, records every change, and never labels untested CAD “ready”.</p><a className="button light" href="https://github.com/scottbez1/splitflap" target="_blank">Open reference project <ExternalLink size={15}/></a><small>Image: Scott Bezek / splitflap, Apache-2.0.</small></div></section>

    <section className="section buy" id="buy"><div className="section-heading"><p className="eyebrow">BUYING PLAN · AUD · CHECKED 04 SEP 2026</p><h2>Cheap path, with the catches visible.</h2><p>Prices and stock move. Confirm voltage, fitted headers/connectors and delivered total before paying.</p></div><div className="calculator"><div><label>Character modules</label><div className="segmented"><button onClick={()=>setModuleCount(1)} className={moduleCount===1?'active':''}>1</button><button onClick={()=>setModuleCount(2)} className={moduleCount===2?'active':''}>2</button></div></div><div><small>ROUGH MODULE PARTS</small><strong>AU${estimate.toFixed(0)}–{(estimate+moduleCount*7.5).toFixed(0)}</strong><span>+ controller AU$55–95 + shipping + filament</span></div></div><div className="table-wrap"><table><thead><tr><th>Use</th><th>Part</th><th>Qty</th><th>Price</th><th>Supplier</th><th>Watch for</th></tr></thead><tbody>{bom.map(row=><tr key={row.item}><td><span className="pill">{row.group}</span></td><td>{row.item}</td><td>{row.qty}</td><td><strong>{row.price}</strong></td><td><a href={row.url} target="_blank">{row.source} <ExternalLink size={12}/></a></td><td>{row.note}</td></tr>)}</tbody></table></div><div className="download-row"><a className="button primary" href="/modular-splitflap-bom.csv" download><Download size={16}/> Download BOM (.csv)</a><p>*Estimate includes small allowances for printed material/hardware, but not cross-shop delivery. Marketplace examples are not endorsements.</p></div></section>

    <section className="section architecture" id="architecture"><div className="section-heading"><p className="eyebrow">SYSTEM ARCHITECTURE</p><h2>The Pi coordinates. Every character thinks.</h2></div><div className="signal-flow"><div className="node brain"><small>CONTROLLER</small><strong>Raspberry Pi Zero</strong><span>USB → RS-485 adapter</span><code>SET 02 41</code></div><div className="bus"><span>A · B · GND</span><ArrowRight/></div><div className="node module"><small>MODULE 02</small><strong>ESP32-C3</strong><span>Validates ID → homes → drives → reports</span><code>OK 02 POS 41</code></div></div><div className="architecture-grid"><article><Cpu/><h3>What each module owns</h3><ul><li>Unique ID in MCU flash</li><li>52-entry character map</li><li>Motor sequencing and measured step count</li><li>Hall home and fault recovery</li><li>Current position while powered</li></ul></article><article><PackageOpen/><h3>What the Pi owns</h3><ul><li>Layout: ID → row/column</li><li>Text, clock, animations and web UI</li><li>Discovery and status polling</li><li>Scheduling and integrations</li><li>Never direct motor GPIO</li></ul></article><article><AlertTriangle/><h3>Critical bus correction</h3><p>RS-485 wants a linear trunk with short stubs and 120 Ω at its two ends. Four identical edge contacts are mechanically attractive, but arbitrary 2D branches and loops are not automatically reliable. Prove two modules first; later add configurable routing or active repeaters.</p><a href="https://www.ti.com/lit/an/slla272d/slla272d.pdf" target="_blank">TI RS-485 design guide <ExternalLink size={12}/></a></article></div></section>

    <section className="section alphabet"><div className="section-heading"><p className="eyebrow">CHARACTER ORDER · FORWARD ONLY</p><h2>One explicit 52-position map</h2><p>Forward-only is mechanically safer than “shortest direction.” The controller computes steps modulo 52; the ratchet/pawl keeps flaps seated.</p></div><div className="alphabet-grid">{alphabet.map((c,i)=><div key={i}><small>{String(i).padStart(2,'0')}</small><strong>{c==='SPACE'?'—':c}</strong><span>{c==='SPACE'?'SPACE':''}</span></div>)}</div><a className="text-link" href="/character-map.csv" download><Download size={14}/> Download character map</a></section>

    <section className="section wiring"><div className="section-heading"><p className="eyebrow">NO-SOLDER WIRING RULES</p><h2>Plug, clamp, screw. Nothing else.</h2></div><div className="rule-grid"><article><b>01</b><h3>Buy fitted connectors</h3><p>Loose headers in a bag fail your rule. Photos are not enough—ask the seller to confirm they arrive soldered.</p></article><article><b>02</b><h3>Separate prototype from product</h3><p>Dupont leads are fine on the bench. Production modules need factory-assembled locking connectors and strain relief.</p></article><article><b>03</b><h3>Common ground</h3><p>Logic and RS-485 need a shared reference. Keep motor current out of thin signal leads.</p></article><article><b>04</b><h3>Power off before moving wires</h3><p>Never rewire while powered. Fuse the shared supply and cover exposed terminals.</p></article></div><div className="warning"><AlertTriangle/><p><strong>Never laser-cut PVC or unknown plastic.</strong> PVC can release toxic, corrosive gases. Use a guillotine, punch, drag knife or professional die cutting after checking the material data sheet.</p><a href="https://www.troteclaser.com/en-gb/resources/faqs/unsuitable-materials-for-laser-processing" target="_blank">Trotec safety guidance <ExternalLink size={12}/></a></div></section>

    <section className="section manufacture" id="manufacture"><div className="section-heading"><p className="eyebrow">FROM PROTOTYPE TO MANUFACTURE</p><h2>Do not buy tooling before reliability.</h2></div><div className="maker-grid">{makers.map(m=><a href={m.url} target="_blank" key={m.name}><span>{m.place}</span><h3>{m.name}</h3><p>{m.job}</p><strong>{m.price}</strong><ExternalLink size={16}/></a>)}</div><div className="production-path"><div><b>1–2</b><span>Hand-cut CR80 + printed jig</span></div><ArrowRight/><div><b>10–50</b><span>Plotter/knife samples + assembled PCB quote</span></div><ArrowRight/><div><b>100+</b><span>Steel-rule die + PCBA + incoming inspection</span></div></div></section>

    <section className="section sources"><div className="section-heading"><p className="eyebrow">RESEARCH NOTES</p><h2>What is proven—and what is not.</h2></div><div className="source-columns"><div><h3>High-confidence starting points</h3><a href="https://github.com/scottbez1/splitflap" target="_blank">Scott Bezek splitflap — Apache-2.0</a><a href="https://documentation.espressif.com/esp32-c3_datasheet_en.html" target="_blank">Espressif ESP32-C3 datasheet</a><a href="https://www.analog.com/en/products/max3485.html" target="_blank">Analog Devices MAX3485</a><a href="https://oshwa.org/definition/" target="_blank">OSHWA open-hardware definition</a></div><div><h3>Still requires physical evidence</h3><p>Printer tolerances, custom pawl shape, actual motor gearing, flap fall reliability, pogo wear, contact resistance and a branching 2D network.</p><p>No custom CAD or PCB is called production-ready until it passes the gates above.</p></div><div><h3>Licence plan</h3><p>CERN-OHL-P-2.0 for original hardware, MIT for software, CC BY 4.0 for original docs/art. Preserve third-party notices. Adam G Makes is CC BY-NC-SA; do not copy its files into a permissive release.</p></div></div></section>

    <footer><div className="brand"><span className="brand-mark">MS</span><span>MODULAR SPLITFLAP</span></div><p>Research build · prices checked 04 September 2026 · Australia</p><a href="#top">Back to top ↑</a></footer>
  </main>;
}
