'use client';

import {useEffect,useState} from 'react';
import {AlertTriangle,ArrowDown,Check,ChevronRight,Download,ExternalLink,ShoppingCart,Wrench,Zap} from 'lucide-react';

const buyNow=[
 ['1','ESP32-C3 Mini board','Must say “pre-soldered headers”','$7.60','https://core-electronics.com.au/esp32-c3-mini-dev-board-risc-v-processor-wi-fi-bt5-smd-compatible.html'],
 ['1','28BYJ-48 motor + ULN2003 driver','Buy 5 V first; motor must include its 5-pin plug','about $7 delivered','https://www.ebay.com.au/b/Unbranded-Industrial-Stepper-Motors/9723/bn_18937908'],
 ['1','Hall sensor module','Must arrive as a complete board with fitted 3-pin header','about $4.78 for 5','https://www.ebay.com.au/shop/sensor-hall-effect?_nkw=sensor+hall+effect'],
 ['1','Small neodymium magnet','3×2 mm is suitable for the first sensor test','$0.43 each; $8.60 MOQ','https://magnet.com.au/products/neodymium-disc-3mm-x-2mm'],
 ['1','Female-to-female jumper ribbon','40 pre-crimped wires; no crimper needed','$3.20','https://core-electronics.com.au/prototyping/prototyping-wire/female-female.html'],
 ['6','Blank CR80 PVC cards','Cut each in half to create 12 test flaps','from shared $25–27 pack','https://csid.com.au/blank-cards/white-recycled-pvc-cards/'],
 ['2','M3 machine screws + nuts + washers','One drum axle and one adjustable pawl mount','check your parts drawer',''],
 ['1','USB-C data cable','Programs and powers the ESP32 during bench testing','use one you own',''],
];

const buyLater=[
 ['After 12-flap test passes','Second motor, ESP32-C3 and Hall module','Build the second identical character module'],
 ['After the full drum passes','2 × MAX3485 3.3 V RS-485 modules','One belongs inside every character module'],
 ['After both modules work alone','Raspberry Pi Zero W + microSD + power supply','The separate controller/brain module'],
 ['When connecting the Pi','USB-to-RS-485 adapter with screw terminals','Lets the Pi speak RS-485 without soldering'],
 ['After 1,000 reliable cycles','Pogo pins, edge PCBs and joining magnets','Do not let the connector distract from the flap mechanism'],
 ['After dimensions are frozen','Custom assembled PCBs and die-cut flaps','Production step, not a first prototype purchase'],
];

const phases=[
 {n:'0',title:'Before you buy anything',goal:'Confirm the project is ready for a cheap experiment.',items:['Create a free GitHub account and install OpenSCAD plus Arduino IDE.','Print a 20 mm calibration cube; measure it with your calipers or ruler.','Check that your printer can make a clean 0.2 mm layer and 0.4 mm nozzle print.','Read the shopping-list rules below. Never order a board with loose headers.','Set aside AU$30 for this first 12-flap test—not for the finished two-module system.'],pass:'You know your printer works and every electronic listing is genuinely plug-in.'},
 {n:'1',title:'Buy only the starter test parts',goal:'Spend the minimum needed to find out whether the mechanism can work.',items:['Buy the eight lines marked BUY NOW.','Do not buy the Raspberry Pi yet.','Do not buy pogo pins, 100+ magnets, a custom PCB or die-cut tooling.','Combine suppliers where delivery costs more than the part.','Save screenshots of the exact motor voltage and connector photos.'],pass:'All parts arrive with fitted connectors; nothing requires soldering.'},
 {n:'2',title:'Test the electronics on the table',goal:'Make the motor turn and the Hall sensor detect a magnet before printing a full module.',items:['Plug the motor into the ULN2003 socket.','Use four jumper wires from ESP32 GPIO pins to IN1–IN4.','Connect ULN2003 GND and ESP32 GND.','Connect the Hall module to 3.3 V, GND and one input pin.','Upload a basic forward-step test; move the magnet past the sensor and watch the serial output.'],pass:'Motor completes 100 forward revolutions and HOME is detected every time.'},
 {n:'3',title:'Print the tiny mechanical tests',goal:'Learn your real tolerances without wasting a large print.',items:['Print four flap-slot samples: nominal, +0.1, +0.2 and +0.3 mm.','Print the motor-shaft socket, M3 axle hole and magnet pocket as separate coupons.','Choose the loosest flap slot with no sideways wobble.','Write the winning clearance values down.','Never force a magnet into a pocket; adjust and reprint.'],pass:'Flaps swing freely, axle rotates, motor socket grips and magnet seats safely.'},
 {n:'4',title:'Build the 12-flap mechanism',goal:'Prove gravity, drum and pawl geometry cheaply.',items:['Cut six CR80 cards exactly in half to make 12 flap halves.','Punch identical pivot tabs using a printed jig.','Print a 12-position test drum and side frame using your measured clearances.','Fit the M3 free-side axle and adjustable pawl.','Turn by hand for 100 cycles, then connect the motor for 500 cycles.'],pass:'Zero jams, flaps fall cleanly and the pawl holds the displayed face.'},
 {n:'5',title:'Only now build module 01',goal:'Scale the proven mechanism to all 52 positions.',items:['Use 52 flap halves: 26 CR80 cards.','Keep the proven 54×43×0.762 mm flap-half geometry for Rev A.','Use a roughly 60 mm drum and forward-only rotation.','Install the motor, Hall sensor, magnet and ESP32-C3.','Measure actual steps per revolution; do not assume the internet value is correct.','Assign and save module ID 01.'],pass:'Module 01 completes 1,000 mixed character moves without a jam or home error.'},
 {n:'6',title:'Build the identical second module',goal:'Prove that modules are replaceable building blocks.',items:['Print the same files with the same settings.','Install the same parts and assign ID 02.','Test module 02 alone for 1,000 moves.','Buy and connect one 3.3 V MAX3485 board per module.','Wire A-to-A, B-to-B and GND-to-GND as a short straight bus.'],pass:'One computer command can send module 01 and module 02 to different positions.'},
 {n:'7',title:'Build the Raspberry Pi controller',goal:'Replace the test computer with the permanent brain.',items:['Buy a Raspberry Pi Zero W, a 16 GB or larger microSD and a proper power supply.','Write Raspberry Pi OS Lite to the microSD—this is why the Pi needs storage.','Plug a USB-to-RS-485 adapter into the Pi using an OTG adapter.','Connect adapter A/B/GND to the same straight bus.','Run controller software that sends address + target position and reads status.'],pass:'The Pi independently commands IDs 01 and 02; unplugging it leaves both letters visible.'},
 {n:'8',title:'Test module-to-module connectors last',goal:'Validate the snap-together interface without hiding mechanical faults.',items:['Print alignment pegs/sockets first; magnets provide holding force only.','Prototype large contact pads and spring pogo pins on one joining edge.','Route RS-485 as a linear trunk; do not create arbitrary branches or loops yet.','Join and separate the modules 250 times.','Measure voltage during simultaneous movement and count packet errors.'],pass:'No sliding, resets, brownouts or dropped commands across 250 connection cycles.'},
];

export default function Home(){
 const [done,setDone]=useState<string[]>([]); useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem('guide-progress')||'[]'))}catch{}},[]);
 const toggle=(n:string)=>setDone(v=>{const x=v.includes(n)?v.filter(i=>i!==n):[...v,n];localStorage.setItem('guide-progress',JSON.stringify(x));return x});
 return <main>
  <header><a className="logo" href="#top">MODULAR<br/>SPLITFLAP</a><nav><a href="#before">Before buying</a><a href="#buy">Buy now</a><a href="#steps">Build order</a><a href="#later">Buy later</a></nav><a className="repo" href="https://github.com/Mr0ks/modular-splitflap" target="_blank">GitHub <ExternalLink size={13}/></a></header>
  <section className="intro" id="top"><div><p className="kicker">START HERE · BEGINNER VERSION</p><h1>Exactly what to do.<br/><em>In the right order.</em></h1><p className="lead">First prove a cheap 12-flap mechanism. Then build one 52-position module. Then duplicate it. Then add the Raspberry Pi. Buy parts only when the previous test passes.</p><a className="cta" href="#before">Begin before buying <ArrowDown size={17}/></a></div><aside><span>YOUR FIRST PURCHASE</span><strong>AU$25–35</strong><p>One motor test set, one module chip, one sensor, 12 test flaps and plug-in wires.</p><small>Delivery and owned tools vary.</small></aside></section>
  <section className="plain-warning"><AlertTriangle/><div><strong>Important correction</strong><p>There is not yet a physically tested custom CAD/PCB set for your new design. The website must guide experiments honestly—it cannot promise that untested printable parts will work. The first stages create the measurements needed for reliable CAD.</p></div></section>

  <section className="section" id="before"><div className="section-title"><span>00</span><div><p className="kicker">BEFORE BUYING</p><h2>What you already have—and what is missing.</h2></div></div><div className="inventory"><article className="have"><h3>You already have</h3><ul><li><Check/>3D printer</li><li><Check/>Soldering iron—not required</li><li><Check/>Multimeter</li></ul></article><article><h3>You still need eventually</h3><ul><li>Small ruler or digital calipers</li><li>Side cutters / craft knife</li><li>Small Phillips screwdriver</li><li>Raspberry Pi and microSD—but not today</li><li>Pre-crimped wires—no crimping tool</li></ul></article><article className="stop"><h3>Do not buy yet</h3><ul><li>Custom PCB order</li><li>Die-cut flap tooling</li><li>Pogo pins or edge PCBs</li><li>Parts for 10+ modules</li><li>Injection moulds</li></ul></article></div></section>

  <section className="section buy" id="buy"><div className="section-title"><span>01</span><div><p className="kicker">SHOPPING LIST · BUY NOW</p><h2>Buy this for one 12-flap test.</h2><p>Every electronic board must arrive assembled with fitted pins. If a listing shows loose header strips, choose another listing.</p></div></div><div className="buy-table"><div className="buy-head"><span>QTY</span><span>PART</span><span>EXACT REQUIREMENT</span><span>PRICE</span><span>LINK</span></div>{buyNow.map((x,i)=><div className="buy-row" key={x[1]}><b>{x[0]}</b><strong>{x[1]}</strong><p>{x[2]}</p><span>{x[3]}</span>{x[4]?<a href={x[4]} target="_blank">Supplier <ExternalLink size={12}/></a>:<i>Local shop</i>}</div>)}</div><div className="buy-bottom"><ShoppingCart/><p><strong>Checkout rule:</strong> keep the delivered starter basket near AU$30. Marketplace prices change; combine orders and do not pay AU$10 shipping for a AU$3 part.</p><a href="/modular-splitflap-bom.csv" download><Download size={14}/> Download full BOM</a></div></section>

  <section className="section sequence" id="steps"><div className="section-title"><span>02–08</span><div><p className="kicker">THE COMPLETE ORDER</p><h2>Build, test, then unlock the next stage.</h2><p>Tap a stage only after its PASS box is true. Your progress saves on this device.</p></div></div><div className="progress"><span style={{width:(done.length/phases.length*100)+'%'}}/><b>{done.length} of {phases.length} stages passed</b></div><div className="timeline">{phases.map(p=><article className={done.includes(p.n)?'phase completed':'phase'} key={p.n}><button onClick={()=>toggle(p.n)} aria-label={'Mark stage '+p.n+' complete'}>{done.includes(p.n)?<Check/>:p.n}</button><div><p className="goal">GOAL · {p.goal}</p><h3>{p.title}</h3><ol>{p.items.map(i=><li key={i}>{i}</li>)}</ol><div className="pass"><Check/><p><strong>PASS BEFORE CONTINUING</strong>{p.pass}</p></div></div></article>)}</div></section>

  <section className="section later" id="later"><div className="section-title"><span>WAIT</span><div><p className="kicker">SHOPPING LIST · BUY LATER</p><h2>Purchase these only when unlocked.</h2></div></div><div className="later-grid">{buyLater.map((x,i)=><article key={x[1]}><span>{String(i+1).padStart(2,'0')}</span><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>

  <section className="section architecture"><div className="section-title"><span>RULE</span><div><p className="kicker">WHO CONTROLS WHAT</p><h2>Every character has its own chip.</h2></div></div><div className="flow"><div><small>RASPBERRY PI</small><strong>“Module 02, go to position 41.”</strong><p>Stores layout, text, clocks and the web interface.</p></div><ChevronRight/><div><small>RS-485 BUS</small><strong>Address + command + checksum</strong><p>Carries messages; does not drive motors.</p></div><ChevronRight/><div><small>MODULE 02 MCU</small><strong>Homes, counts and drives itself.</strong><p>Own ID, motor, sensor and local fault handling.</p></div></div></section>

  <section className="section safety"><Wrench/><div><h2>Three rules that do not change</h2><p><b>1.</b> No soldering means fitted headers, plug-in motor sockets, screw terminals and later factory-assembled PCBs.</p><p><b>2.</b> Move forward only. Reversing a split-flap drum can lift or jam flaps.</p><p><b>3.</b> Never laser-cut PVC. Cut cards mechanically with a jig, guillotine or punch.</p></div><Zap/></section>
  <footer><strong>MODULAR SPLITFLAP</strong><p>Rev A beginner roadmap · prices checked 04 September 2026</p><a href="#top">Back to top ↑</a></footer>
 </main>
}
